[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
multisynq = "CBTq287t3pjLuwgHMcmkq1ErQu7EW16aBLy79JjKsTDc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
multisynq-demo = "ts-node scripts/multisynq-demo.ts"
burn-mint = "ts-node  scripts/burn-mint.ts"
adaptive-mesh = "ts-node  scripts/adaptive-mesh-demo.ts"

